### ISSUE TITLE
The experience of using tags in CPP is very fragmented

### ISSUE THREAD

**Issue by nozomanai** [getnamo/GlobalEventSystem-Unreal#31]
At present, there are no GamePlayTag related functions provided on the cpp side. Why not consider adding a Tag related version, and I think FGESEventContext may be redundant on the cpp side and can be packaged more simply

If it is simplified, function parameters can be passed directly without creating redundant structure parameters
![image](https://github.com/user-attachments/assets/b5c769ab-f357-4f9e-85b1-838d208445c0)

```c
FString FGESHandler::AddLambdaListener(UObject* Context, FGameplayTag EventTag, const TFunction<void()>& ReceivingLambda)
{
	FString Domain;
	FString Event;
	UGlobalEventSystemBPLibrary::Conv_TagToDomainAndEvent(EventTag, Domain, Event);
	FGESEventContext EventInfo;
	EventInfo.Domain = Domain;
	EventInfo.Event = Event;
	EventInfo.WorldContext = Context;
	return AddLambdaListener(EventInfo,ReceivingLambda);
}
```

**Comment by getnamo** [comment]
The Gameplay Tag variants were largely for blueprint workflow based on dev requests in the past.

That said I will gladly merge a convenience c++ function with tags like the above if you make a pull request with the code. 

I wouldn't get rid of the event context struct as I do prefer the double string context for event filtering.
